### ISSUE TITLE
FFI (?) Problems

### ISSUE THREAD

**Issue by thoughtflare** [FrigoEU/purescript-endpoints-express#1]
[This commit](https://github.com/thoughtflare/purescript-endpoints-express/commit/6ce439187ceeaa32604fd10e5a816a2941c59a74) fixes `example/` source tree, however I have faced a JS problem, which I can't solve (described in the commit message).
Please look into it. Also I wonder if you have plans on maintaining this project. If not, please suggest ways to mitigate this JS issue or perhaps a library that utilizes the same lightweight "newtype"-based approach to type safety between browser and backend. I'm coming from Haskell background and trying full-stack PureScript these days, so I'd be interested in learning all the intricacies of PureScript stack while being reasonably productive in actually making something useful :)

**Comment by FrigoEU** [comment]
Hey,  I'm definitely maintaining this package. I'm not actively working on it to add all kinds of stuff, but rather add things that I need whenever a project I use it for needs something. I extracted the example to its own repo, it's much easier to work with. You can find it here:
 
https://github.com/FrigoEU/purescript-endpoints-express-example. 

The example was definitely outdated. Check out the new repo and let me know if there's any problems.

**Comment by thoughtflare** [comment]
Thank you! I'll make sure it works and make a PR removing `example/` directory from this repo and updating the README. Thank you for this library.

**Comment by FrigoEU** [comment]
Hey, maybe I wasn't clear, but I already did that 😀. The master branch of this package already has the example/ folder deleted and the Readme adapted. If you see any other possible improvements, you're of course welcome to make a PR or ask me directly.

**Comment by thoughtflare** [comment]
I tested and it works.
